"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 3000

[directory]
style = "cyan"

[git_branch]
style = "bright-white"

[git_status]
style = "yellow"

[character]
success_symbol = "[◆](bold green)"
error_symbol = "[◆](bold red)"